version: "3.8"

services:
  web:
    image: website:latest
    volumes:
      - /dist/:/var/www/rbk6.dev/public/
    networks:
      - webnet
    restart: always

networks:
  webnet:
    driver: bridge
